---
title: "figure2"
author: "Jaime So"
date: "8/27/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(reshape2)
```

#Generate Plots for Figure 2
##T.b. gambiense samples show a bias towards expression of type B VSG
* BLAST tree generated by Bill Wickstead

##Fig. 2B
```{r}

palette2B <- c("#ffd968", "#eb7d2f", "#9a1b30")

typeCompare <- read_csv("FigureData/Supptable4_nterm_method_compare.csv")

tree_compare <- typeCompare %>%
  filter(blastTree_type != "not done") %>%
  .[!grepl("Gambiense", .$original_seqID), ] %>%
  mutate(VSG = "Lister 427") %>%
  mutate( 
    assessment = case_when(
      HMM_type == network_type & HMM_type == blastTree_type ~ "All methods agree",
      HMM_type == network_type & HMM_type != blastTree_type ~ "HMM & Network graph agree",
      HMM_type == blastTree_type & HMM_type != network_type ~ "HMM & BLASTp-tree agree",
      blastTree_type == network_type & blastTree_type != HMM_type ~ "BLASTp-tree & network",
      blastTree_type !=network_type & network_type != HMM_type ~ "all disagree")) %>%
  mutate( 
    count = case_when(
      HMM_type == network_type & HMM_type == blastTree_type ~ "3",
      HMM_type == network_type & HMM_type != blastTree_type ~ "2",
      HMM_type == blastTree_type & HMM_type != network_type ~ "2",
      blastTree_type == network_type & blastTree_type != HMM_type ~ "2",
      blastTree_type !=network_type & network_type != HMM_type ~ "0")) %>%
  select(VSG, assessment, count)


ggplot(tree_compare, aes(x = count, fill = assessment)) + 
  geom_bar() +
  xlab("number of methods in agreement")


gam_compare <- typeCompare %>%
  .[grepl("Gambiense", .$original_seqID), ] %>%
  mutate(VSG = "gHAT Patient")%>%
  mutate( 
    assessment = case_when(
      HMM_type == network_type & HMM_type == blastTree_type ~ "All methods agree",
      HMM_type == network_type & HMM_type != blastTree_type ~ "HMM & Network graph agree",
      HMM_type == blastTree_type & HMM_type != network_type ~ "HMM & BLASTp-tree agree",
      blastTree_type == network_type & blastTree_type != HMM_type ~ "BLASTp-tree & network",
      blastTree_type !=network_type & network_type != HMM_type ~ "all disagree")) %>%
  mutate( 
    count = case_when(
      HMM_type == network_type & HMM_type == blastTree_type ~ "3",
      HMM_type == network_type & HMM_type != blastTree_type ~ "2",
      HMM_type == blastTree_type & HMM_type != network_type ~ "2",
      blastTree_type == network_type & blastTree_type != HMM_type ~ "2",
      blastTree_type !=network_type & network_type != HMM_type ~ "0")) %>%
  select(VSG, assessment, count)


all_compare <- rbind(tree_compare, gam_compare)

Fig2B <- ggplot(all_compare, aes(x = VSG, fill = assessment)) +theme_classic(base_size = 22) +
  geom_bar(position = "fill") +
  scale_fill_manual(values = palette2B) +
  ylab ("Proportion") +
  xlab("VSG set") +
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size = 20), axis.text.y = element_text(size = 20), axis.title = element_text(size = 20),legend.title = element_text(size = 16), legend.text = element_text(size = 14))
Fig2B

```

##Fig. 2C
```{r}
view(read_csv("FigureData/Supptable3_tbgVSGexpression.csv"))

palette2C <- c("#9EC3E0", "#2A84C6", "#0B4063", "#E17AA2", "#A1324D", "lightgrey")
# plot number of VSG by type per patient
Fig2C <- read_csv("FigureData/Supptable3_tbgVSGexpression.csv") %>% 
  select(c("patient_number", "cdHit_ID", "nterm_typesubtype")) %>% 
  distinct() %>% 
  dplyr::group_by(patient_number, nterm_typesubtype) %>% 
  dplyr::summarise(total = n()) %>%
  ggplot(aes(x = as.factor(patient_number), y = total, fill = nterm_typesubtype)) +
  geom_bar(stat = "identity", size = 0.8) + 
  scale_fill_manual(values = palette2C) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 6)) +
  theme_classic(base_size = 22) + 
  ylab("Number of VSGs") + 
  labs(fill = "N-terminal Subtype") +
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size = 20), axis.text.y = element_text(size = 20), axis.title = element_text(size = 20),legend.title = element_text(size = 16), legend.text = element_text(size = 14))+
  xlab("Patient")
Fig2C

```